apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: lease-a-car-api
    service: lease-calculation-service
  annotations: 
    timestamp: "+%H:%M:%S %d/%m/%y"
  name: lease-calculation-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: lease-calculation-service
  template:
    metadata:
      labels:
        api: lease-a-car-api
        service: lease-calculation-service
    spec:
      restartPolicy: Always
      containers:
      - image: hakktastic/lease-calculation-service:0.1.3
        imagePullPolicy: Always
        name: lease-calculation-service
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:  
            path: /lease-calculation-service/actuator/health/liveness  
            port: 8080  
          initialDelaySeconds: 60 
          periodSeconds: 5
          failureThreshold: 10 
        readinessProbe:  
          httpGet:  
            path: /lease-calculation-service/actuator/health/readiness  
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    api: lease-a-car-api
    service: lease-calculation-service
  name: lease-calculation-service
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: lease-calculation-service
  type: NodePort