version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - network-lease-a-car-api
      
  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "9411:9411"
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - network-lease-a-car-api
      
  eureka-naming-server:
    image: hakktastic/netflix-eureka-naming-server:0.0.5-SNAPSHOT
    container_name: eureka-naming-server
    build:
      context: ./netflix-eureka-naming-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - zipkin-server
    networks:
      - network-lease-a-car-api
      
  zuul-api-gateway-server:
    image: hakktastic/netflix-zuul-api-gateway-server:0.0.5-SNAPSHOT
    container_name: zuul-api-gateway-server
    build:
      context: ./netflix-zuul-api-gateway-server
      dockerfile: Dockerfile
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8765:8765"
    restart: always
    depends_on:
      - eureka-naming-server
    networks:
      - network-lease-a-car-api

  customer-service:
    image: hakktastic/customer-service:0.0.5-SNAPSHOT
    container_name: customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - zuul-api-gateway-server
    networks:
      - network-lease-a-car-api
           
  car-service:
    image: hakktastic/car-service:0.0.5-SNAPSHOT
    container_name: car-service
    build:
      context: ./car-service
      dockerfile: Dockerfile
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - zuul-api-gateway-server
    networks:
      - network-lease-a-car-api

  interest-rate-calculation-service:
    image: hakktastic/interest-rate-calculation-service:0.0.5-SNAPSHOT
    container_name: interest-rate-calculation-service
    build:
      context: ./interest-rate-calculation-service
      dockerfile: Dockerfile
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      - zuul-api-gateway-server
    networks:
      - network-lease-a-car-api

  lease-calculation-service:
    image: hakktastic/lease-calculation-service:0.0.5-SNAPSHOT
    container_name: lease-calculation-service
    build:
      context: ./lease-calculation-service
      dockerfile: Dockerfile
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - zuul-api-gateway-server
      - customer-service
      - car-service
      - interest-rate-calculation-service
    networks:
      - network-lease-a-car-api     
networks:
  network-lease-a-car-api: