version: '3.7'

services:     

  customer-service:
    image: hakktastic/customer-service:0.1.1-SNAPSHOT
    container_name: customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    networks:
      - network-lease-a-car-api
           
  car-service:
    image: hakktastic/car-service:0.1.1-SNAPSHOT
    container_name: car-service
    build:
      context: ./car-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    networks:
      - network-lease-a-car-api

  interest-rate-calculation-service:
    image: hakktastic/interest-rate-calculation-service:0.1.1-SNAPSHOT
    container_name: interest-rate-calculation-service
    build:
      context: ./interest-rate-calculation-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    networks:
      - network-lease-a-car-api

  lease-calculation-service:
    image: hakktastic/lease-calculation-service:0.1.1-SNAPSHOT
    container_name: lease-calculation-service
    build:
      context: ./lease-calculation-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - customer-service
      - car-service
      - interest-rate-calculation-service
    networks:
      - network-lease-a-car-api     

networks:
  network-lease-a-car-api: